name: text
description: separate module for localizations and text
authors:
  - bgoncharuck
  - yarimmer
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
dev_dependencies: